public class Exercicio1 {
 public static void main(String[] args) {
  int[] vetor = new int[] { 2, 4, 6, 8, 10 };

  for (int i = 0; i < 6; i++)
    System.out.println(vetor[i]);

  catch (ArrayIndexOutOfBoundsException exc) {
    System.out.println("Final do vetor!");
  }
 }
}
Erros:
- O bloco for precisa estar dentro de um try.
- O catch não pode existir sozinho fora do bloco try.

Correção:
public class Exercicio1 {
 public static void main(String[] args) {
  int[] vetor = new int[] { 2, 4, 6, 8, 10 };

  try {
    for (int i = 0; i < 6; i++)
      System.out.println(vetor[i]);
  } catch (ArrayIndexOutOfBoundsException exc) {
    System.out.println("Final do vetor!");
  }
 }
}
